version: "3.8"
services:
  rabbitmq:
    container_name: Twitch-rabbitmq
    hostname: rabbit
    image: rabbitmq:3-management
    ports:
     - "5672:5672"
     - "15672:15672"
     - "15692:15692"
  # mssql:
  #   container_name: Twitch-mssql
  #   hostname: mssql
  #   image: mcr.microsoft.com/mssql/server
  #   ports:
  #    - "1433:1433"
  #   environment:
  #     SA_PASSWORD: "MTTwitchSample1"
  #     ACCEPT_EULA: "Y"
  redis:
    image: redis
    container_name: Twitch-redis
    ports:
      - "6379:6379"
  # mongo:
  #   image: "mongo"
  #   container_name: Twitch-mongo
  #   ports:
  #   - '27017-27019:27017-27019'

  twitch.sample.orderapi:
    image: ${DOCKER_REGISTRY-}twitchsampleorderapi
    build:
      context: .
      dockerfile: Twitch.Sample.OrderApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "52358:80"
    depends_on:
      - rabbitmq

  twitch.sample.service:
    image: ${DOCKER_REGISTRY-}twitchsampleservice
    build:
      context: .
      dockerfile: Twitch.Sample.Service/Dockerfile
    depends_on:
      - rabbitmq
      - redis
